// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCStdqXgYRvEyM3FGCTdOIk8CNRTMyfpIM',
    appId: '1:1020855975805:web:593ca991868825592fd614',
    messagingSenderId: '1020855975805',
    projectId: 'moneyapp-372c6',
    authDomain: 'moneyapp-372c6.firebaseapp.com',
    storageBucket: 'moneyapp-372c6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDZwkHMvKHipoCLSvi1qf9Tx8fH4lwG_A',
    appId: '1:1020855975805:android:5ef66f0439071daa2fd614',
    messagingSenderId: '1020855975805',
    projectId: 'moneyapp-372c6',
    storageBucket: 'moneyapp-372c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYnE_BbO3vnU10Yw69fzzJJvCgiGRxQgo',
    appId: '1:1020855975805:ios:db23d821a1e9ae4d2fd614',
    messagingSenderId: '1020855975805',
    projectId: 'moneyapp-372c6',
    storageBucket: 'moneyapp-372c6.firebasestorage.app',
    iosBundleId: 'com.example.moneyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYnE_BbO3vnU10Yw69fzzJJvCgiGRxQgo',
    appId: '1:1020855975805:ios:db23d821a1e9ae4d2fd614',
    messagingSenderId: '1020855975805',
    projectId: 'moneyapp-372c6',
    storageBucket: 'moneyapp-372c6.firebasestorage.app',
    iosBundleId: 'com.example.moneyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCStdqXgYRvEyM3FGCTdOIk8CNRTMyfpIM',
    appId: '1:1020855975805:web:dbe866bb05918f012fd614',
    messagingSenderId: '1020855975805',
    projectId: 'moneyapp-372c6',
    authDomain: 'moneyapp-372c6.firebaseapp.com',
    storageBucket: 'moneyapp-372c6.firebasestorage.app',
  );
}
